### PR TITLE
rpc-sys: rework packagelist call for apk

### PR DESCRIPTION
**Pull request by efahl**
Parse the apk files to produce the packagelist.

Reads both the 'installed' file to collect all package names and versions.  If the 'all' parameter is false, then only the packages listed in the 'world' file are retained.

Remaining issue:
There is no ABI version information in any of the apk files, so the returned file names have not been cleaned.  This is contrary to the opkg version, which cleaned the package names, and is a bug that needs to be fixed once the ABI version are available.

Fixes: openwrt/openwrt#16907

### CODE REVIEW

**Comment by efahl** [comment]
Tested on x86/64 snapshot main openwrt/openwrt@56952678

Built a whole image containing this fix, sysupgraded an existing VM and ran three variants: `{"all":true}`, '{"all":false}` and no parameters.  Confirmed that all three showed proper and expected output.

**Comment by dibdot** [comment]
@efahl Many thanks, works like a charme!
Re-tested successfully in my own builds for an APU1 (x86) and an OpenWrt One (mediatek). 
The autodetection in adblock and banIP is up & running again (after I've fixed a mess with json  keys and hyphens in my code ... :smile: )

Thanks again!

Tested-by: Dirk Brenken <dev@brenken.org>

**Comment by efahl** [comment]
That last push added a couple more error checks for the `world` file being corrupted in different ways.  (Fixed a seg fault if the file was missing the final newline.)

**Comment by dangowrt** [comment]
The issue of missing ABIVersion information has been discussed in detail with APK developers:
Link: https://gitlab.alpinelinux.org/alpine/apk-tools/-/merge_requests/152

**Comment by efahl** [comment]
> missing ABIVersion information 

So, how do we want to proceed with this?  
1) Accept this PR to get the apk-based framework in place and resolve the ABI versioning as a separate issue, then circle around and fix things here later.
2) Wait until ABI versioning has a fix, then fix this PR after that's done.

I'd prefer 1, as it lets me test a lot more things (specifically in `owut`), even if the ABIed names are wrong, at least it doesn't just crash on startup...

**Comment by dangowrt** [comment]
@aparcar @ynezz Is there any plan in place to add ABIVersion metadata (or rather: the package name without appended ABIVersion)?

@efahl I agree that we should merge this, we will anyway have to soon change it again once APKv3-style database will be used also for the installed-db.

**Comment by efahl** [comment]
> we will anyway have to soon change it again once APKv3-style database

Yeah, that's why I waited a couple weeks to submit this PR, I thought maybe I'd get some word on the v3 transition, but decided to just get something in sooner...

**Comment by Ansuel** [comment]
for ABI I can add a downstream patch while I found time/apk maintainers implement the correct proposed solution...

For v3... it will be a nightmare to change this code but whatever priority is to have the thing working.

**Comment by efahl** [comment]
> For v3... it will be a nightmare to change this code but whatever priority is to have the thing working.

My initial thought on that was pretty hacky, but just `exec("apk list --installed --manifest")` to get it working...

So, who's going to be brave and just commit this PR as-is?  😁

**Comment by dangowrt** [comment]
> My initial thought on that was pretty hacky, but just `exec("apk list --installed --manifest")` to get it working...

We don't want to do that because that means you would need to have `apk` installed on the target. One of the design goals of the sysupgrade server is that you do not need a package manager on the target itself, but only a (potentially stripped) list of installed packages.

**Comment by Ansuel** [comment]
It's stable and won't change... At max entry will be added but given how
the schema works its easy to align

Il Mer 27 Nov 2024, 00:33 efahl ***@***.***> ha scritto:

**Comment by iwowcn** [comment]
root@ImmortalWrt:~# owut check
owut - OpenWrt Upgrade Tool 2024.11.14~3b5e7bb9-r1 (/usr/bin/owut)
ERROR: ubus: Not found: Failed to invoke function 'packagelist' on object 'rpc-sys'
 from: 'ubus call rpc-sys packagelist { "all": true }'
This is a bug in 'owut/2024.11.14~3b5e7bb9-r1', please report at
  https://github.com/efahl/owut/issues

In [anonymous function](), file /usr/bin/owut, line 103, byte 24:
  called from function [anonymous function] (/usr/bin/owut:240:58)
  called from function [anonymous function] (/usr/bin/owut:245:74)
  called from function collect_packages (/usr/bin/owut:964:69)
  called from function collect_all (/usr/bin/owut:1340:19)
  called from anonymous function (/usr/bin/owut:2026:15)

 `           `  ${issue_url}\n`);`
  Near here -------------------^

**Comment by efahl** [comment]
> we will anyway have to soon change it again once APKv3-style database will be used also for the installed-db.

Does anyone know roughly when the v3 switchover will happen?  I cannot find anything at all on it.

I've been digging through apk source and docs, seeing how feasible it is to write a "small" reader for the v3 .adb files. Thus far I've uncovered three variants on the file, corresponding to the file starting with these magic numbers:
 - `ADB.` = no compression
 - `ADBd` = standard apk "deflate" compression, using zlib - this is the default
 - `ADBc` = custom compression, currently allows zstd

My semi-formed conclusions thus far are:
1) It's probably not going to be all that small if we handle all cases.  (I haven't looked, how big are the zstd libs?)
2) Using `libapk.so` as a standalone is attractive from an implementation perspective, but it's currently 205k (on x86), so ouch.  Also, that sort of breaks the "rpc shouldn't require a package manager" goal.
3) Maybe it would be easiest to just add another make target `libapkreader` to the `apk` build that collects just enough code to dump what's needed for the packagelist.

**Comment by dibdot** [comment]
yep, every interim solution is better than 'utterly broken'. Please go  for it - thanks.

**Comment by robimarko** [comment]
@Ansuel @ynezz Thoughts on merging this?

**Comment by robimarko** [comment]
Thanks! Rebased on top of master and merged!

**Pull request merged**
